name: Check eslint and prettier
on:
  pull_request:
    branches:
      - development
jobs:
  eslint-prettier:
    name: Check eslint and prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run prettier-check
      - name: Lint
        run: npm run lint